### ISSUE TITLE
Support for Netstandard2.0 and therefore net48

### ISSUE THREAD

**Issue by DrNeil** [musement/configcat-configuration-provider#5]
This project is great and useful, however I am still working with a number of net48 (old framework) projects that could benefit from this library, while we upgrade them to dotnet core. 
I have written a PR to enable this library to compile for netstandard2.0 as well as net6.0 providing more options.
[Support for netstandard2.0 in library and net48 in sample app](https://github.com/musement/configcat-configuration-provider/pull/4) 
Let me know your thoughts.

**Comment by rahulvermapropertyme** [comment]
Agree, support for older framework will make this project available to a number of old projects too.

**Comment by kipters** [comment]
I understand the sentiment but supporting older versions of .NET is not a goal for this project. I'm closing this one as WONTFIX, you're welcome to fork the project though.
